# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# class TestRefusejoin():
#   def setup_method(self, method):
#     self.driver = webdriver.Chrome()
#     self.vars = {}
  
#   def teardown_method(self, method):
#     self.driver.quit()
  
#   def test_refusejoin(self):
    # self.driver.get("http://localhost:8080/")
    # self.driver.set_window_size(1440, 900)
    # self.driver.find_element(By.CSS_SELECTOR, "#enter_login > span").click()
    # self.driver.find_element(By.ID, "login_nickname_input").click()
    # self.driver.find_element(By.ID, "login_nickname_input").send_keys("yy")
    # self.driver.find_element(By.ID, "login_password_input").click()
    # self.driver.find_element(By.ID, "login_password_input").send_keys("yy123456..")
    # self.driver.find_element(By.ID, "login_btn").click()
    # time.sleep(3)
    # team=self.driver.find_element(By.CSS_SELECTOR, ".el-menu-item:nth-child(5)")
    # team.click()
    # time.sleep(3)
    # self.driver.find_element(By.CSS_SELECTOR, ".el-menu--vertical > .el-menu-item:nth-child(2)").click()
    # time.sleep(3)
    # self.driver.find_element(By.CSS_SELECTOR, ".card-list:nth-child(1) .el-card__body:nth-child(1) .el-button--danger > span").click()
    # self.driver.find_element(By.ID, "user_select_item").click()
    # time.sleep(3)
    # self.driver.find_element(By.CSS_SELECTOR, ".big_content:nth-child(3) .choose_content_text").click()
    # time.sleep(3)
    # self.driver.find_element(By.CSS_SELECTOR, ".account_page_content:nth-child(5) > .account_page_type").click()
    # time.sleep(3)
    # assert self.driver.switch_to.alert.text == "确定要退出吗？"
    # self.driver.switch_to.alert.accept()
  

def run_team_test():
    driver = webdriver.Chrome()
    
    try:
      driver.get("http://localhost:8080/")
      driver.set_window_size(1440, 900)
        
      driver.find_element(By.CSS_SELECTOR, "#enter_login > span").click()
      driver.find_element(By.ID, "login_nickname_input").click()
      driver.find_element(By.ID, "login_nickname_input").send_keys("yy")
      driver.find_element(By.ID, "login_password_input").click()
      driver.find_element(By.ID, "login_password_input").send_keys("yy123456..")
      driver.find_element(By.ID, "login_btn").click()
      time.sleep(3)
      team=driver.find_element(By.CSS_SELECTOR, ".el-menu-item:nth-child(5)")
      team.click()
      time.sleep(3)
      driver.find_element(By.CSS_SELECTOR, ".el-menu--vertical > .el-menu-item:nth-child(2)").click()
      time.sleep(3)
      driver.find_element(By.CSS_SELECTOR, ".card-list:nth-child(1) .el-card__body:nth-child(1) .el-button--danger > span").click()
      driver.find_element(By.ID, "user_select_item").click()
      time.sleep(3)
      driver.find_element(By.CSS_SELECTOR, ".big_content:nth-child(3) .choose_content_text").click()
      time.sleep(3)
      driver.find_element(By.CSS_SELECTOR, ".account_page_content:nth-child(5) > .account_page_type").click()
      time.sleep(3)
        
      assert driver.switch_to.alert.text == "确定要退出吗？"
      driver.switch_to.alert.accept()
        
    finally:
        driver.quit()

    return {'status': 'success'}